### ISSUE TITLE
Decrypt stage 2 key

### ISSUE THREAD

**Issue by Beercow** [hasherezade/petya_recovery#4]
Just curious if you plan on adding the ability to decrypt the stage 2 key without having to use the web site. this functionality is in the https://github.com/leo-stone/hack-petya code. I would attempt it myself but I am not familiar in coding in c or go.

**Comment by hasherezade** [comment]
it is already done, see the new code :)

**Comment by Beercow** [comment]
I'll have to take a look. I know your blog states "I updated my decoder – now if if cannot give you the Stage1 key, it will give you the data necessary to supply to the Leo’s web application". I have not tried it out yet so I was checking to see if it will give you the key without having to enter the information on the site.
